//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.EmpDepManSupPositions = new HashSet<EmpDepManSupPosition>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.ItemRequisitions = new HashSet<ItemRequisition>();
        }
    
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual T_User T_User { get; set; }
        public virtual ICollection<EmpDepManSupPosition> EmpDepManSupPositions { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions { get; set; }
    }
}
