//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDepManSupPosition
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> SupervisorRoleID { get; set; }
        public int ManagerRoleID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
