//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmpDependants = new HashSet<EmpDependant>();
            this.EmpDepManSupPositions = new HashSet<EmpDepManSupPosition>();
            this.EmpSalaryBenefits = new HashSet<EmpSalaryBenefit>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.Log_Table = new HashSet<Log_Table>();
            this.T_User1 = new HashSet<T_User>();
            this.Tasks = new HashSet<Task>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.DriverToVehicleAssignments = new HashSet<DriverToVehicleAssignment>();
            this.FleetVehicleBookingReports = new HashSet<FleetVehicleBookingReport>();
            this.FleetVehicleBookingReports1 = new HashSet<FleetVehicleBookingReport>();
            this.FleetVehicleBookingRequests = new HashSet<FleetVehicleBookingRequest>();
            this.FleetVehicleBookingRequests1 = new HashSet<FleetVehicleBookingRequest>();
            this.FleetVehicleBookingRequests2 = new HashSet<FleetVehicleBookingRequest>();
            this.FleetVehicleMaintenanceRequests = new HashSet<FleetVehicleMaintenanceRequest>();
            this.FleetVehicleMaintenanceRequests1 = new HashSet<FleetVehicleMaintenanceRequest>();
            this.FleetVehicleMaintenanceRequests2 = new HashSet<FleetVehicleMaintenanceRequest>();
            this.FleetVehiclePartsRequests = new HashSet<FleetVehiclePartsRequest>();
            this.FleetVehiclePartsRequests1 = new HashSet<FleetVehiclePartsRequest>();
            this.ItemRequisitions = new HashSet<ItemRequisition>();
            this.ItemRequisitions1 = new HashSet<ItemRequisition>();
            this.ItemRequisitions2 = new HashSet<ItemRequisition>();
            this.ItemRequisitions3 = new HashSet<ItemRequisition>();
            this.ProcurementPurchaseRequests = new HashSet<ProcurementPurchaseRequest>();
            this.ProcurementPurchaseRequests1 = new HashSet<ProcurementPurchaseRequest>();
        }
    
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int CountyAddressID { get; set; }
        public string ImagePath { get; set; }
        public int CountyOfOriginID { get; set; }
        public string PlaceOfBirth { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Age { get; set; }
        public int GenderID { get; set; }
        public int StatusID { get; set; }
        public int PositionID { get; set; }
        public int MaritalStatusID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual County County { get; set; }
        public virtual County County1 { get; set; }
        public virtual ICollection<EmpDependant> EmpDependants { get; set; }
        public virtual ICollection<EmpDepManSupPosition> EmpDepManSupPositions { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Position Position { get; set; }
        public virtual Status Status { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual ICollection<EmpSalaryBenefit> EmpSalaryBenefits { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<Log_Table> Log_Table { get; set; }
        public virtual ICollection<T_User> T_User1 { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual ICollection<DriverToVehicleAssignment> DriverToVehicleAssignments { get; set; }
        public virtual ICollection<FleetVehicleBookingReport> FleetVehicleBookingReports { get; set; }
        public virtual ICollection<FleetVehicleBookingReport> FleetVehicleBookingReports1 { get; set; }
        public virtual ICollection<FleetVehicleBookingRequest> FleetVehicleBookingRequests { get; set; }
        public virtual ICollection<FleetVehicleBookingRequest> FleetVehicleBookingRequests1 { get; set; }
        public virtual ICollection<FleetVehicleBookingRequest> FleetVehicleBookingRequests2 { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceRequest> FleetVehicleMaintenanceRequests { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceRequest> FleetVehicleMaintenanceRequests1 { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceRequest> FleetVehicleMaintenanceRequests2 { get; set; }
        public virtual ICollection<FleetVehiclePartsRequest> FleetVehiclePartsRequests { get; set; }
        public virtual ICollection<FleetVehiclePartsRequest> FleetVehiclePartsRequests1 { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions1 { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions2 { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions3 { get; set; }
        public virtual ICollection<ProcurementPurchaseRequest> ProcurementPurchaseRequests { get; set; }
        public virtual ICollection<ProcurementPurchaseRequest> ProcurementPurchaseRequests1 { get; set; }
    }
}
