//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetVehiclePartsRequest
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public string VehiclePartName { get; set; }
        public string Description { get; set; }
        public int UrgencyID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ProcurementApprovalID { get; set; }
        public Nullable<int> ProcurementManagerID { get; set; }
        public string ProcurementManagerMessage { get; set; }
        public Nullable<int> FinanceManagerApprovalID { get; set; }
        public Nullable<int> FinanceManagerID { get; set; }
        public string FinanceManagerMessage { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FleetVehicle FleetVehicle { get; set; }
        public virtual LevelOfUrgency LevelOfUrgency { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
