//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetVehicleMaintenanceRequest
    {
        public FleetVehicleMaintenanceRequest()
        {
            this.FleetVehicleMaintenanceReports = new HashSet<FleetVehicleMaintenanceReport>();
        }
    
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public int VehicleStatusID { get; set; }
        public string MaintenanceDetail { get; set; }
        public int MaintenanceCauseID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int DriverID { get; set; }
        public Nullable<int> FleetManagerApprovalID { get; set; }
        public Nullable<int> FleetManagerID { get; set; }
        public string FleetManagerMessage { get; set; }
        public Nullable<int> FinanceManagerApprovalID { get; set; }
        public Nullable<int> FinanceManagerID { get; set; }
        public string FinanceManagerMessage { get; set; }
        public Nullable<int> RequestStatusID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceReport> FleetVehicleMaintenanceReports { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
