//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetVehicleBookingRequest
    {
        public FleetVehicleBookingRequest()
        {
            this.FleetVehicleBookingReports = new HashSet<FleetVehicleBookingReport>();
        }
    
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string Location { get; set; }
        public int CountyID { get; set; }
        public string BookingDescription { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<int> AssignedDriverID { get; set; }
        public Nullable<int> AssignedVehicleID { get; set; }
        public Nullable<int> DepartmentManagerApprovalID { get; set; }
        public Nullable<int> DepartmentManagerID { get; set; }
        public string DepartmentManagerMessage { get; set; }
        public Nullable<int> FleetManagerApprovalID { get; set; }
        public Nullable<int> FleetManagerID { get; set; }
        public string FleetManagerMessage { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual County County { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual FleetVehicle FleetVehicle { get; set; }
        public virtual ICollection<FleetVehicleBookingReport> FleetVehicleBookingReports { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
