//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetVehicleBookingReport
    {
        public int ID { get; set; }
        public int BookingID { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public System.TimeSpan DispatchTime { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public System.TimeSpan ReturnTime { get; set; }
        public string ReportDescription { get; set; }
        public bool Incident { get; set; }
        public Nullable<int> IncidentTypeID { get; set; }
        public Nullable<int> ResolutionTypeID { get; set; }
        public string ResolutionDescription { get; set; }
        public int DriverID { get; set; }
        public Nullable<int> FleetManagerApprovalID { get; set; }
        public Nullable<int> FleetManagerID { get; set; }
        public string FleetManagerMessage { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FleetVehicleBookingRequest FleetVehicleBookingRequest { get; set; }
        public virtual IncidentType IncidentType { get; set; }
        public virtual ResolutionType ResolutionType { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
