//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetVehicle
    {
        public FleetVehicle()
        {
            this.FleetVehicleBookingRequests = new HashSet<FleetVehicleBookingRequest>();
            this.FleetVehiclePartsRequests = new HashSet<FleetVehiclePartsRequest>();
            this.FleetDriverVehicleAssignments = new HashSet<FleetDriverVehicleAssignment>();
        }
    
        public int ID { get; set; }
        public string VehicleCode { get; set; }
        public string VIN { get; set; }
        public decimal Mileage { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int TypeID { get; set; }
        public int Year { get; set; }
        public int OwnershipStatusID { get; set; }
        public string Color { get; set; }
        public int FuelTankSize { get; set; }
        public string FuelTankType { get; set; }
        public int UnitID { get; set; }
        public System.DateTime RecieveDate { get; set; }
        public int RecieveConditionID { get; set; }
        public int VehicleStatusID { get; set; }
        public int RegistrationStatusID { get; set; }
        public string PlateNumber { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual FleetVehicleOwnership FleetVehicleOwnership { get; set; }
        public virtual FleetVehicleRegistrationStatu FleetVehicleRegistrationStatu { get; set; }
        public virtual FleetVehicleStatu FleetVehicleStatu { get; set; }
        public virtual FleetVehicleType FleetVehicleType { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        public virtual ICollection<FleetVehicleBookingRequest> FleetVehicleBookingRequests { get; set; }
        public virtual ICollection<FleetVehiclePartsRequest> FleetVehiclePartsRequests { get; set; }
        public virtual ICollection<FleetDriverVehicleAssignment> FleetDriverVehicleAssignments { get; set; }
    }
}
