//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<County> Counties { get; set; }
        public DbSet<DegreeCredential> DegreeCredentials { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<EmpDependant> EmpDependants { get; set; }
        public DbSet<EmpDepManSupPosition> EmpDepManSupPositions { get; set; }
        public DbSet<EmpEducation> EmpEducations { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmpRole> EmpRoles { get; set; }
        public DbSet<EmpSalaryBenefit> EmpSalaryBenefits { get; set; }
        public DbSet<FavLogoTitle> FavLogoTitles { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<LeaveRequest> LeaveRequests { get; set; }
        public DbSet<LeaveType> LeaveTypes { get; set; }
        public DbSet<LevelOfUrgency> LevelOfUrgencies { get; set; }
        public DbSet<Log_Table> Log_Table { get; set; }
        public DbSet<MaritalStatu> MaritalStatus { get; set; }
        public DbSet<PayGrade> PayGrades { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<ProcessType> ProcessTypes { get; set; }
        public DbSet<Relationship> Relationships { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<T_User> T_User { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TaskAction> TaskActions { get; set; }
        public DbSet<TaskRating> TaskRatings { get; set; }
        public DbSet<TaskReport> TaskReports { get; set; }
        public DbSet<WorkExperience> WorkExperiences { get; set; }
        public DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public DbSet<FieldOffice> FieldOffices { get; set; }
        public DbSet<FleetVehicle> FleetVehicles { get; set; }
        public DbSet<FleetVehicleBookingReport> FleetVehicleBookingReports { get; set; }
        public DbSet<FleetVehicleBookingRequest> FleetVehicleBookingRequests { get; set; }
        public DbSet<FleetVehicleMaintenanceApprovalAction> FleetVehicleMaintenanceApprovalActions { get; set; }
        public DbSet<FleetVehicleMaintenanceReport> FleetVehicleMaintenanceReports { get; set; }
        public DbSet<FleetVehicleMaintenanceRequest> FleetVehicleMaintenanceRequests { get; set; }
        public DbSet<FleetVehicleOwnership> FleetVehicleOwnerships { get; set; }
        public DbSet<FleetVehiclePartsRequest> FleetVehiclePartsRequests { get; set; }
        public DbSet<FleetVehicleReceivedCondition> FleetVehicleReceivedConditions { get; set; }
        public DbSet<FleetVehicleRegistrationStatu> FleetVehicleRegistrationStatus { get; set; }
        public DbSet<FleetVehicleStatu> FleetVehicleStatus { get; set; }
        public DbSet<FleetVehicleType> FleetVehicleTypes { get; set; }
        public DbSet<IncidentType> IncidentTypes { get; set; }
        public DbSet<ItemRequisition> ItemRequisitions { get; set; }
        public DbSet<ProcumentProcuredItem> ProcumentProcuredItems { get; set; }
        public DbSet<ProcurementPurchaseRequest> ProcurementPurchaseRequests { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ReceivedCondition> ReceivedConditions { get; set; }
        public DbSet<RequestStatu> RequestStatus { get; set; }
        public DbSet<ResolutionType> ResolutionTypes { get; set; }
        public DbSet<UnitOfMeasurement> UnitOfMeasurements { get; set; }
        public DbSet<FleetDriverVehicleAssignment> FleetDriverVehicleAssignments { get; set; }
        public DbSet<RequestAction> RequestActions { get; set; }
    }
}
