//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentType
    {
        public IncidentType()
        {
            this.FleetVehicleBookingReports = new HashSet<FleetVehicleBookingReport>();
        }
    
        public int ID { get; set; }
        public string IncidentType1 { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<FleetVehicleBookingReport> FleetVehicleBookingReports { get; set; }
    }
}
