//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequisition
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public string Item { get; set; }
        public string ItemDescription { get; set; }
        public decimal Quantity { get; set; }
        public int UnitID { get; set; }
        public int UrgencyID { get; set; }
        public Nullable<int> ManagerApprovalID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<System.DateTime> ManagerApprovalDate { get; set; }
        public string ManagerMessage { get; set; }
        public Nullable<int> ProcurementManagerApprovalID { get; set; }
        public Nullable<int> ProcurementManagerID { get; set; }
        public Nullable<System.DateTime> ProcurementManagerApprovalDate { get; set; }
        public string ProcurementManagerMessage { get; set; }
        public Nullable<int> ProcurementOfficerID { get; set; }
        public Nullable<bool> PocurementOfficerDeliver { get; set; }
        public Nullable<decimal> DeliveryQuantity { get; set; }
        public Nullable<System.DateTime> ProcurementOfficerDeliverDate { get; set; }
        public Nullable<bool> EmployeeReceived { get; set; }
        public Nullable<System.DateTime> EmployeeReceivedDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual LevelOfUrgency LevelOfUrgency { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
