//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int LeaveTypeID { get; set; }
        public string Message { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string NumberOfDays { get; set; }
        public bool isSupervisorActionNeeded { get; set; }
        public Nullable<int> SupervisorActionID { get; set; }
        public string SupervisorComment { get; set; }
        public bool isManagerActionNeeded { get; set; }
        public Nullable<int> ManagerActionID { get; set; }
        public string ManagerComment { get; set; }
        public bool isHRSupervisorActionNeeded { get; set; }
        public Nullable<int> HRSupervisorActionID { get; set; }
        public string HRSupervisorComment { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<System.DateTime> SupervisorActionDate { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<System.DateTime> ManagerActionDate { get; set; }
        public Nullable<int> HRSupervisorID { get; set; }
        public Nullable<System.DateTime> HRSupervisorActionDate { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual RequestAction RequestAction { get; set; }
    }
}
