//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.EmpDepManSupPositions = new HashSet<EmpDepManSupPosition>();
            this.Employees = new HashSet<Employee>();
            this.EmpRoles = new HashSet<EmpRole>();
        }
    
        public int ID { get; set; }
        public string PositionName { get; set; }
        public string Description { get; set; }
        public string PositionGrade { get; set; }
        public bool isSupervisory { get; set; }
        public bool isManagerial { get; set; }
        public bool isTopManagement { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<EmpDepManSupPosition> EmpDepManSupPositions { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmpRole> EmpRoles { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
