//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.Addresses = new HashSet<Address>();
            this.DegreeCredentials = new HashSet<DegreeCredential>();
            this.Departments = new HashSet<Department>();
            this.EmpDependants = new HashSet<EmpDependant>();
            this.EmpEducations = new HashSet<EmpEducation>();
            this.Employees = new HashSet<Employee>();
            this.EmpRoles = new HashSet<EmpRole>();
            this.EmpSalaryBenefits = new HashSet<EmpSalaryBenefit>();
            this.FavLogoTitles = new HashSet<FavLogoTitle>();
            this.Genders = new HashSet<Gender>();
            this.LeaveActions = new HashSet<LeaveAction>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.LeaveTypes = new HashSet<LeaveType>();
            this.LevelOfUrgencies = new HashSet<LevelOfUrgency>();
            this.Log_Table = new HashSet<Log_Table>();
            this.MaritalStatus = new HashSet<MaritalStatu>();
            this.PayGrades = new HashSet<PayGrade>();
            this.Positions = new HashSet<Position>();
            this.Relationships = new HashSet<Relationship>();
            this.Status = new HashSet<Status>();
            this.Tasks = new HashSet<Task>();
            this.TaskActions = new HashSet<TaskAction>();
            this.TaskRatings = new HashSet<TaskRating>();
            this.TaskReports = new HashSet<TaskReport>();
            this.TaskReports1 = new HashSet<TaskReport>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.DeliveryStatus = new HashSet<DeliveryStatu>();
            this.DriverToVehicleAssignments = new HashSet<DriverToVehicleAssignment>();
            this.FieldOffices = new HashSet<FieldOffice>();
            this.FleetVehicles = new HashSet<FleetVehicle>();
            this.FleetVehicleBookingReports = new HashSet<FleetVehicleBookingReport>();
            this.FleetVehicleBookingRequests = new HashSet<FleetVehicleBookingRequest>();
            this.FleetVehicleMaintenanceApprovalActions = new HashSet<FleetVehicleMaintenanceApprovalAction>();
            this.FleetVehicleMaintenanceReports = new HashSet<FleetVehicleMaintenanceReport>();
            this.FleetVehicleMaintenanceRequests = new HashSet<FleetVehicleMaintenanceRequest>();
            this.FleetVehicleOwnerships = new HashSet<FleetVehicleOwnership>();
            this.FleetVehiclePartsRequests = new HashSet<FleetVehiclePartsRequest>();
            this.FleetVehicleReceivedConditions = new HashSet<FleetVehicleReceivedCondition>();
            this.FleetVehicleRegistrationStatus = new HashSet<FleetVehicleRegistrationStatu>();
            this.FleetVehicleStatus = new HashSet<FleetVehicleStatu>();
            this.FleetVehicleTypes = new HashSet<FleetVehicleType>();
            this.ItemRequisitions = new HashSet<ItemRequisition>();
            this.ProcumentProcuredItems = new HashSet<ProcumentProcuredItem>();
            this.ProcurementPurchaseRequests = new HashSet<ProcurementPurchaseRequest>();
            this.UnitOfMeasurements = new HashSet<UnitOfMeasurement>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool isActive { get; set; }
        public bool isAdmin { get; set; }
        public bool isSeniorManagement { get; set; }
        public bool isITOfficerSupervisor { get; set; }
        public bool isITOfficer { get; set; }
        public bool isHRManager { get; set; }
        public bool isHRSupervisor { get; set; }
        public bool isHROfficerPayroll { get; set; }
        public bool isHROfficerGeneral { get; set; }
        public bool isProcurementManager { get; set; }
        public bool isProcurementSupervisor { get; set; }
        public bool isProcurementOfficer { get; set; }
        public bool isFleetManager { get; set; }
        public bool isFleetSupervisor { get; set; }
        public bool isFleetOfficer { get; set; }
        public bool isDriver { get; set; }
        public bool isMaintenanceManager { get; set; }
        public bool isMaintenanceSupervisor { get; set; }
        public bool isMaintenanceOfficer { get; set; }
        public bool isGeneralEmployeeManager { get; set; }
        public bool isGeneralEmployeeSupervisor { get; set; }
        public bool isGeneralEmployee { get; set; }
        public bool isHRDept { get; set; }
        public bool isITDept { get; set; }
        public bool isProcumentDept { get; set; }
        public bool isFleetDept { get; set; }
        public bool isMaintenanceDept { get; set; }
        public bool isGeneralDept { get; set; }
        public bool isSeniorManagementDept { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<DegreeCredential> DegreeCredentials { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<EmpDependant> EmpDependants { get; set; }
        public virtual ICollection<EmpEducation> EmpEducations { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EmpRole> EmpRoles { get; set; }
        public virtual ICollection<EmpSalaryBenefit> EmpSalaryBenefits { get; set; }
        public virtual ICollection<FavLogoTitle> FavLogoTitles { get; set; }
        public virtual ICollection<Gender> Genders { get; set; }
        public virtual ICollection<LeaveAction> LeaveActions { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<LeaveType> LeaveTypes { get; set; }
        public virtual ICollection<LevelOfUrgency> LevelOfUrgencies { get; set; }
        public virtual ICollection<Log_Table> Log_Table { get; set; }
        public virtual ICollection<MaritalStatu> MaritalStatus { get; set; }
        public virtual ICollection<PayGrade> PayGrades { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<Status> Status { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskAction> TaskActions { get; set; }
        public virtual ICollection<TaskRating> TaskRatings { get; set; }
        public virtual ICollection<TaskReport> TaskReports { get; set; }
        public virtual ICollection<TaskReport> TaskReports1 { get; set; }
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual ICollection<DeliveryStatu> DeliveryStatus { get; set; }
        public virtual ICollection<DriverToVehicleAssignment> DriverToVehicleAssignments { get; set; }
        public virtual ICollection<FieldOffice> FieldOffices { get; set; }
        public virtual ICollection<FleetVehicle> FleetVehicles { get; set; }
        public virtual ICollection<FleetVehicleBookingReport> FleetVehicleBookingReports { get; set; }
        public virtual ICollection<FleetVehicleBookingRequest> FleetVehicleBookingRequests { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceApprovalAction> FleetVehicleMaintenanceApprovalActions { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceReport> FleetVehicleMaintenanceReports { get; set; }
        public virtual ICollection<FleetVehicleMaintenanceRequest> FleetVehicleMaintenanceRequests { get; set; }
        public virtual ICollection<FleetVehicleOwnership> FleetVehicleOwnerships { get; set; }
        public virtual ICollection<FleetVehiclePartsRequest> FleetVehiclePartsRequests { get; set; }
        public virtual ICollection<FleetVehicleReceivedCondition> FleetVehicleReceivedConditions { get; set; }
        public virtual ICollection<FleetVehicleRegistrationStatu> FleetVehicleRegistrationStatus { get; set; }
        public virtual ICollection<FleetVehicleStatu> FleetVehicleStatus { get; set; }
        public virtual ICollection<FleetVehicleType> FleetVehicleTypes { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions { get; set; }
        public virtual ICollection<ProcumentProcuredItem> ProcumentProcuredItems { get; set; }
        public virtual ICollection<ProcurementPurchaseRequest> ProcurementPurchaseRequests { get; set; }
        public virtual ICollection<UnitOfMeasurement> UnitOfMeasurements { get; set; }
    }
}
