//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskReports = new HashSet<TaskReport>();
        }
    
        public int ID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AssignTo { get; set; }
        public int LevelOfUrgencyID { get; set; }
        public string AttachFilePath { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LevelOfUrgency LevelOfUrgency { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual ICollection<TaskReport> TaskReports { get; set; }
    }
}
