//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasurement
    {
        public UnitOfMeasurement()
        {
            this.FleetVehicles = new HashSet<FleetVehicle>();
            this.ItemRequisitions = new HashSet<ItemRequisition>();
            this.ProcumentProcuredItems = new HashSet<ProcumentProcuredItem>();
            this.ProcurementPurchaseRequests = new HashSet<ProcurementPurchaseRequest>();
        }
    
        public int ID { get; set; }
        public string MeasuringUnit { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<FleetVehicle> FleetVehicles { get; set; }
        public virtual ICollection<ItemRequisition> ItemRequisitions { get; set; }
        public virtual ICollection<ProcumentProcuredItem> ProcumentProcuredItems { get; set; }
        public virtual ICollection<ProcurementPurchaseRequest> ProcurementPurchaseRequests { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
